### ISSUE TITLE
Reload page and problem re-load?

### ISSUE THREAD

**Issue by dzalkind** [sora-ryu/WEIS-Visualization#10]
One of my main barriers to using this tool is that it needs to be re-launched for each case.  On Kestrel, this requires a number of steps.  Could we have a separate page/input where the user can copy the path of the `vizInput.yaml` and re-load the file for visualization?

**Comment by mayankchetan** [comment]
High Priority

**Comment by dzalkind** [comment]
Clarifying that I'm not talking about having multiple instances visualized at the same time, but the ability to re-load a new instance in the same browser window.

**Comment by sora-ryu** [comment]
Solved - now, able to reload vizinput yaml file by clicking reload button at home page. Whenever user makes updates on their file and hit the button, it re-reads the file.
