### ISSUE TITLE
Timeseries Subplots

### ISSUE THREAD

**Issue by dzalkind** [sora-ryu/WEIS-Visualization#13]
I have a strong preference for plotting the timeseries in subplots rather than on all the same plot.  Here are a few normal use cases that don't make sense to plot on the same axis.

<img width="556" alt="image" src="https://github.com/sora-ryu/WEIS-Visualization/assets/65573423/782396e4-4bee-4502-9153-7bc2b4a04024">

<img width="563" alt="image" src="https://github.com/sora-ryu/WEIS-Visualization/assets/65573423/18680bad-e7ba-43e9-bbf9-aadbcaa8562e">

**Comment by mayankchetan** [comment]
High Priority

**Comment by sora-ryu** [comment]
Solved
