### ISSUE TITLE
Use Case: Visualize RAFT optimization runs

### ISSUE THREAD

**Issue by mayankchetan** [sora-ryu/WEIS-Visualization#8]

**Comment by dzalkind** [comment]
I added an example here: /projects/weis/dzalkind/visualization_cases/1_raft_opt

Note that there is no case_matrix or DLC inputs.  I can help with/point you to the data for RAFT visualizations.

I get the following error: 

![image](https://github.com/sora-ryu/WEIS-Visualization/assets/65573423/1e8ef6aa-13c1-4f3c-830b-07dd2669b240)

**Comment by sora-ryu** [comment]
Solved by categorizing optimization type with 1-RAFT and 2-OpenFAST
